
services:
    laravelapp:
        container_name: laravelapp
        image: francescoxx/laravelapp:1.0.0
        build: .
        ports:
            - "8000:8000"
        env_file:
            -   .env
        depends_on:
            -   db

    db:
        container_name: db
        image: postgres:latest
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testtask
        volumes:
            -   pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
